# Show all possible defaults keys
defaults:
  data-source: my-ds
  query-interval: 10s
  query-timeout: 5s
  query-value-on-error: -1

# Defined data sources
data-sources:
  my-ds:
    driver: postgres
    properties:
      host: docker.for.mac.localhost
      port: 5433
      user: kojo
      password: kojofitness
      database: kojo_fitness
      sslmode: disable
