{
 "title": "kojo_job table stats",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PanickedJobs",
    "query": "label_values(query_result_kojo_num_panicked_jobs_by_job,type_code)"
   },
   {
    "name": "TypeCode",
    "query": "label_values(query_result_kojo_num_assigned_state_by_job,type_code)"
   }
  ]
 },
 "panels": [
  {
   "title": "$TypeCode: assigned_states in kojo_job table",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_result_kojo_num_assigned_state_by_job{type_code=~\"$TypeCode\", assigned_state!=\"panicked\"}) by (assigned_state)",
     "legendFormat": "{{assigned_state}}"
    }
   ]
  },
  {
   "title": "Oldest Waiting Job",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "query_result_kojo_age_oldest_waiting_job"
    }
   ]
  },
  {
   "title": "Panicked: $PanickedJobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "repeat": "PanickedJobs",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "query_result_kojo_num_panicked_jobs_by_job{type_code=\"$PanickedJobs\"}"
    }
   ]
  },
  {
   "title": "Panicked: $PanickedJobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "query_result_kojo_num_panicked_jobs_by_job{type_code=\"$PanickedJobs\"}"
    }
   ]
  }
 ]
}