version: '2'

services:

  ### Mount Applications ######################################

  applications:
    image: tianon/true
    volumes:
    - ../KojoFitness/:/var/www/html/kojo_fitness.neighborhoods.com

  mysql_data:
    image: tianon/true
    volumes:
    - ./data/mysql:/docker-entrypoint-initdb.d

  pgsql_data:
    image: tianon/true
    volumes:
    - ./data/pgsql:/docker-entrypoint-initdb.d

    ### Kōjō Fitness Container (php-fpm) #########################

  kojo_fitness:
    build:
      context: .
      args:
      - INSTALL_XDEBUG=true
      - COMPOSER_INSTALL=false
    volumes:
    # Shares AWS credentials to the docker container
    - $HOME/.aws:/root/.aws
    - $HOME/.aws:/var/www/.aws
    volumes_from:
    - applications
    env_file:
      - kojo.env

### MySQL Container #########################################

  mysql:
    build:
      context: ./mysql
      args:
      - MYSQL_DATABASE=kojo
      - MYSQL_USER=kojo
      - MYSQL_PASSWORD=kojofitness
      - MYSQL_ROOT_PASSWORD=kojoroot
    volumes:
    - mysql:/var/lib/mysql
    volumes_from:
    - mysql_data
    ports:
    - "3307:3306"

### PostgreSQL PostGis Container ############################

  pgsql:
    build: ./postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    volumes_from:
    - pgsql_data
    ports:
    - "5433:5432"
    environment:
      POSTGRES_DB: kojo
      POSTGRES_USER: kojo
      POSTGRES_PASSWORD: kojofitness

### Redis Container #########################################

  redis:
    build: ./redis
    volumes:
    - redis:/data
    ports:
    - "6380:6379"

### Volumes Setup ###########################################

volumes:
    mysql:
      driver: "local"
    postgres:
      driver: "local"
    redis:
      driver: "local"

### Network Setup ###########################################

networks:
  default:
    driver: bridge
