apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: use-case-47
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mdillon/postgis:11
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kojo
            - name: POSTGRES_USER
              value: kojo
            - name: POSTGRES_PASSWORD
              value: kojofitness
