parameters:
# Redis.
  neighborhoods.kojo.environment.parameters.redis_port: '%env(KOJO_REDIS_PORT)%'
  neighborhoods.kojo.environment.parameters.redis_host: '%env(KOJO_REDIS_HOST)%'
# DB
  neighborhoods.kojo.environment.parameters.database_user_name: '%env(DATABASE_USERNAME)%'
  neighborhoods.kojo.environment.parameters.database_password: '%env(DATABASE_PASSWORD)%'
  neighborhoods.kojo.environment.parameters.database_adapter: '%env(DATABASE_ADAPTER)%'
  neighborhoods.kojo.environment.parameters.database_port: '%env(DATABASE_PORT)%'
  neighborhoods.kojo.environment.parameters.database_host: '%env(DATABASE_HOST)%'
  neighborhoods.kojo.environment.parameters.database_name: '%env(DATABASE_NAME)%'
  neighborhoods.kojo.process.pool.logger.level_filter_mask:
    !php/const \Psr\Log\LogLevel::EMERGENCY: false
    !php/const \Psr\Log\LogLevel::ALERT: false
    !php/const \Psr\Log\LogLevel::CRITICAL: false
    !php/const \Psr\Log\LogLevel::ERROR: false
    !php/const \Psr\Log\LogLevel::WARNING: false
    !php/const \Psr\Log\LogLevel::NOTICE: false
    !php/const \Psr\Log\LogLevel::INFO: true
    !php/const \Psr\Log\LogLevel::DEBUG: true

# Slow down the creation of new jobs after panicking while debugging
#  process_pool_strategy.max_alarm_time: 1000000000
  process_pool_strategy.max_child_processes: 6
  process.pool.logger.formatter.log_format: 'json_pretty_print'
